routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');
	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::post('thay-doi-mat-khau', 'LoginController@postPassword')->name('trangchu.postPassword');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');
	Route::post('thay-doi-dia-chi', 'LoginController@postAddress')->name('trangchu.postAddress');
	Route::get('thay-doi-email', 'LoginController@getChangeEmail')->name('trangchu.getChangeEmail');
	Route::post('thay-doi-email', 'LoginController@postChangeEmail')->name('trangchu.postChangeEmail');
	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');
}); 


Route::namespace('Admin')->group(function(){
	Route::get('login','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('login','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/DonhangController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Donhangs\StoreRequest;
use App\Model\Donhang;
use App\Model\OrderDetail;
use Illuminate\Support\Facades\Auth;
use Input;
use Carbon\Carbon;
use App\Model\Member;
use App\Model\Cauhinh;
use App\Model\Sanpham;


class DonhangController extends Controller
{
    private $member;
    private $donhang;
    private $orderDetail;
    private $cauhinh;
    private $sanpham;
    
    public function __construct(
                                Member      $member,
                                Donhang     $donhang,
                                OrderDetail $orderDetail,
                                Cauhinh     $cauhinh,
                                Sanpham     $sanpham
                                )
    {
        $this->member           = $member;
        $this->donhang          = $donhang;
        $this->orderDetail      = $orderDetail;
        $this->cauhinh          = $cauhinh;
        $this->sanpham          = $sanpham;
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $data['donhang']   = $this->donhang->index();

        return view('admin.module.donhangs.donhang-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['sanpham'] = $this->orderDetail->getOrderDetail($id);
        $data['donhang'] = $this->donhang->getDonhang($id);
        return view('admin.module.donhangs.donhang-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id,StoreRequest $req)
    {
        if (isset($_POST['btnUndoXacnhan']))
        {
            $data = array('status_paid' => 0);
            $this->donhang->updateDonhang($data,$id);
            return redirect()->back();
        }
        if (isset($_POST['btnXacnhan']))
        {
            $data = array('status_paid' => 1);
            $this->donhang->updateDonhang($data,$id);
            return redirect()->back();
        }
        if (isset($_POST['btnUndoGiaohang']))
        {
            $data = array('status_move' => 1);
            $this->donhang->updateDonhang($data,$id);
            return redirect()->back();
        }
        if (isset($_POST['btnGiaohang']))
        {
            $data = array('status_move' => 0);
            $this->donhang->updateDonhang($data,$id);
            return redirect()->back();
        }
        if($req->ajax())
        {            
            $id = $req->id;
            $data = DB::table('skl_order')->find($id);
        }
        die(json_encode($html));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->donhang->destroyDonhang($id);
            }
            return redirect()->route('donhang.index')->with('alertsuc','Xóa thành công');
        }
    }
    public function getInhoadon()
    {
        if(Request::get('token'))
        {
            $token = Request::get('token');
            $datadonhang = $this->donhang->getDonhangToken($token);
            if($datadonhang->token == $token)
            {
                $data['sanphamimg']     = $this->sanpham->getSanphamHoadon();
                $data['tenwebsite']     = $this->cauhinh->getData('tenwebsite')->chitiet;
                $data['dienthoai']      = $this->cauhinh->getData('dienthoai')->chitiet;
                $data['diachi']         = $this->cauhinh->getData('title')->chitiet;
                $data['logo']           = $this->cauhinh->getData('photos')->chitiet;
                $data['linkwebsite']    = $this->cauhinh->getData('linkwebsite')->chitiet;
                $data['member']         = $this->member->getMemberEmail($datadonhang->email);
                $data['sanpham']        = $this->orderDetail->getOrderDetail($datadonhang->id);
                $data['donhang']        = $this->donhang->getDonhang($datadonhang->id);
                return view('admin.module.donhangs.inhoadon',$data);
            }
        }
    }
    public function updatedata()
    {
        $data = array(  'hoten'     => Request::get('hoten'),
                        'email'     => Request::get('email'),
                        'sodt'      => Request::get('sodt'),
                        'diachi'    => Request::get('diachi'),
                        'province'  => Request::get('province'),
                        'district'  => Request::get('district'),
                        'ward'      => Request::get('ward'),
                        'ghichu'    => Request::get('ghichu')
                        );
        $datadonhang = $this->donhang->updateDonhang($data, Request::get('id'));
        return Request::all();
        // DB::table('skl_order')->where('id',$req->id)->update($data);
    }
}

resources/views/admin/module/donhangs/coupon-create.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('coupon.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_them')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .edit{
        /*background: #EEECEC;*/
        padding: 10px;
        font-size: 26px;
        font-weight: bold;
        /*border-radius: 5px;*/
    }
</style>
<form action="{{ route('coupon.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <div class="color-line"></div>
                        <span class="edit">{{trans('message.btn_them')}}</span>
                        <div style="margin-bottom: 10px" class="color-line"></div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Mã phiếu</span>
                                            <input value="{{old('id')}}" type="text" name="id" class="form-control" placeholder="Mã phiếu">
                                        </div>
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Ngày bắt đầu</span>
                                            <input value="{{old('begin')}}" type="datetime-local" name="begin" class="form-control" placeholder="Nhập ngày">
                                        </div>
                                    </div>
                                </div>
                               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-1  2">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Money</span>
                                            <input value="{{old('money')}}" type="text" name="money" class="form-control" placeholder="Nhập số tiền">
                                        </div>
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Ngày kết thúc</span>
                                            <input value="{{old('end')}}" type="datetime-local" name="end" class="form-control" placeholder="Nhập ngày">
                                        </div>
                                </div>
                                </div>
                            </div>
                        <div style="padding-top: 30px" class="mg-b-pro-edt custom-pro-edt-ds">
                            <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                            </button>
                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                            </button></div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/donhangs/donhang-list.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{route('index')}}">{{trans('message.trangchu')}}</a> <span class="bread-slash">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.danhsach')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .chuatt{
        background: -webkit-linear-gradient(178deg, #FDE06B  0%, #FDE06B  100%);
        background: linear-gradient(178deg, #FDE06B  0%, #FDE06B  100%);
        border-radius: 8px;
        padding: 7px 5px 7px 5px;
    }
</style>
<div class="product-status mg-tb-15">
    @include('admin.blocks.alert')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>{{trans('message.danhsach_donhang')}}</h4>
                    <div class="add-product">
                        <a href="{{ route('donhang.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                    <table>
                        <tr>
                            <td>
                                <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                            </td>
                            <th>Đơn hàng</th>
                            <th>Ngày đặt</th>
                            <th>Khách hàng</th>
                            <th>Thanh toán</th>
                            <th>Giao hàng</th>
                            <th>Tổng tiền</th>
                        </tr>
                        @foreach($donhang as $item)
                        <tr style="vertical-align: top">
                            
                            <td style="width: 4%">
                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                            </td>
                            <td style="width: 12%">
                                <a href="{{ route('donhang.edit', ['donhang' => $item->id]) }}">#{{$item->id}}</a></td>
                            <td style="width: 18%">
                                <?php
                                    $date = date_create($item->created_at);
                                    echo date_format($date, 'd-m-Y H:i');
                                ?>
                            </td>
                            <td style="width: 18%">{{$item->hoten}}</td>
                            <td style="width: 16%">
                                @if($item->status_paid == 0)
                                <span class="chuatt">Chưa thanh toán</span>
                                @else
                                <span style="font-weight: bold;">Đã thanh toán</span>
                                @endif
                            </td>
                            <td style="width: 16%">
                                @if($item->status_move == 0)
                                <span class="chuatt">Chưa giao hàng</span>
                                @else
                                <span style="font-weight: bold;">Đã giao hàng</span>
                                @endif
                            </td>
                            <td style="width: 16%">
                                <?php echo convert_money($item->tongtien)." VNĐ";?>
                            </td>                 
                        </tr>
                        @endforeach
                    </table>
                    {{ method_field('DELETE') }}
                    <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="pd-setting-ed-delete">
                        <i class="fa fa-trash-o" aria-hidden="true"></i> {{trans('message.btn_xoa')}}
                    </button>
                    </form>
                     {{$donhang->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection