routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');
	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::post('thay-doi-mat-khau', 'LoginController@postPassword')->name('trangchu.postPassword');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');
	Route::post('thay-doi-dia-chi', 'LoginController@postAddress')->name('trangchu.postAddress');
	Route::get('thay-doi-email', 'LoginController@getChangeEmail')->name('trangchu.getChangeEmail');
	Route::post('thay-doi-email', 'LoginController@postChangeEmail')->name('trangchu.postChangeEmail');
	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');
}); 


Route::namespace('Admin')->group(function(){
	Route::get('login','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('login','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/DmspController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dmsps\StoreRequest;
use App\Model\Dmsp;
use Illuminate\Support\Facades\Auth;
use Input;
use Illuminate\Database\QueryException;

class DmspController extends Controller
{
    private $dmsp;

    public function __construct(
                                Dmsp $dmsp
                                )
    {
        $this->dmsp          = $dmsp;
        
    }

    public function getParent()
    {
        $data = [];
        
        $optParent = $this->dmsp->listCateByIdParent(0); 
        foreach($optParent  as $oP)
        {
            $dataOptPar = array('id'     => $oP->id, 
                                'name'   => $oP->name);
            array_push($data, $dataOptPar);

            $optChild = $this->dmsp->listCateByIdParent($oP->id);
            foreach ($optChild as $oC) 
            {
                // Tạo mảng 2 chiều danh mục con
                $dataOptChi= [
                                "id"=>$oC->id,
                                "name"=>"-- ".$oC->name
                             ];
                array_push($data, $dataOptChi);
            }
            
        }
        return $data;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['dmsp']   = $this->dmsp->index();
        
        $data['optArr'] = $this->getParent();

        return view('admin.module.dmsps.dmsp-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['optArr'] = $this->getParent();

        return view('admin.module.dmsps.dmsp-create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {
        $menu    = $this->dmsp->getId();
        if(count($menu) < 9)
        {
            $data = array(
                            'name' => $req->name,
                            'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                            'vitri' => $req->vitri,
                            'id_parent' => $req->id_parent,
                        );
            try {
                 $this->dmsp->storeDmsp($data);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
        elseif($req->id_parent == 0)
        {
            $data = array(
                            'name' => $req->name,
                            'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                            'vitri' => $req->vitri,
                            'id_parent' => $req->id_parent,
                        );
            try {
                 $this->dmsp->storeDmsp($data);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
        else
        {
            return redirect()->back()->with('alerterr','Danh mục con đã đạt số lượng tối đa');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['optArr'] = $this->getParent();

        $data['dmsp'] = $this->dmsp->getDmsp($id);
        return view('admin.module.dmsps.dmsp-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        if (isset($_POST['addTintuc']))
        {
            $data = array(
                        'name' => $req->name,
                        'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                        'vitri' => $req->vitri,
                        'id_parent' => $req->id_parent,
                    );
            try {
                $this->dmsp->updateDmsp($data,$id);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Sửa thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->dmsp->destroyDmsp($id);
            }
            return redirect()->route('dmsp.index')->with('alertsuc','Xóa thành công');
        }
    }
}

resources/views/admin/module/dmsps/dmsp-create.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('dmsp.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_them')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .edit{
        /*background: #EEECEC;*/
        padding: 10px;
        font-size: 26px;
        font-weight: bold;
        /*border-radius: 5px;*/
    }
</style>
<form action="{{ route('dmsp.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <div class="color-line"></div>
                        <span class="edit">{{trans('message.btn_them')}}</span>
                        <div style="margin-bottom: 10px" class="color-line"></div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Tên danh mục</span>
                                            <input value="{{old('name')}}" type="text" name="name" class="form-control" placeholder="Tên danh mục">
                                        </div>
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Alias</span>
                                            <input value="{{old('alias')}}" type="text" name="alias" class="form-control" placeholder="Alias">
                                        </div>
                                    </div>
                                </div>
                               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-1  2">
                                    <div class="review-content-section">
                                    <div class="input-group mg-b-pro-edt">
                                        <span class="input-group-addon">Danh mục</span>
                                        <select name="id_parent" class="form-control pro-edt-select form-control-primary">
                                            <option value="0">Không chọn thể loại</option>
                                            @for($i = 0; $i < count($optArr); $i++)
                                                <option value="{{$optArr[$i]['id']}}">{!!$optArr[$i]['name']!!}</option>
                                            @endfor
                                        </select>
                                    </div>
                                    <div class="input-group mg-b-pro-edt">
                                        <span class="input-group-addon ">Vị trí</span>
                                        <input value="0" value="{{old('vitri')}}" type="text" name="vitri" class="form-control" placeholder="Vị trí">
                                    </div>
                                </div>
                                </div>
                            </div>
                        <div style="padding-top: 30px" class="mg-b-pro-edt custom-pro-edt-ds">
                            <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                            </button>
                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                            </button></div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/dmsps/dmsp-edit.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('dmsp.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_sua')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .edit{
        /*background: #EEECEC;*/
        padding: 10px;
        font-size: 26px;
        font-weight: bold;
        /*border-radius: 5px;*/
    }
</style>
<form action="{{ route('dmsp.update', ['dmsp' => $dmsp->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    {{ method_field('PUT') }}
<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <div class="color-line"></div>
                        <span class="edit">{{trans('message.btn_sua')}}</span>
                        <div class="color-line"></div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Tên danh mục</span>
                                            <input value="{{old('title',$dmsp->name)}}" type="text" name="name" class="form-control" placeholder="Tên danh mục ">
                                        </div>
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Alias</span>
                                            <input value="{{old('alias',$dmsp->alias)}}" type="text" name="alias" class="form-control" placeholder="Alias">
                                        </div>
                                    </div>
                                </div>
                               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                    <div class="input-group mg-b-pro-edt">
                                        <span class="input-group-addon">Danh mục</span>
                                        <select name="id_parent" class="form-control pro-edt-select form-control-primary">
                                            <option value="">Please Choose Category</option>
                                            @if($dmsp->id_parent == 0)
                                                @for($i = 0; $i < count($optArr); $i++)
                                                <option value="{!!$optArr[$i]['id']!!}" {{ $dmsp->id == $optArr[$i]['id'] ? "selected" : "" }}>{!!$optArr[$i]['name']!!}</option>
                                                @endfor
                                            @else
                                            @for($i = 0; $i < count($optArr); $i++)
                                                <option value="{!!$optArr[$i]['id']!!}" {{ $dmsp->id_parent == $optArr[$i]['id'] ? "selected" : "" }}>{!!$optArr[$i]['name']!!}</option>
                                            @endfor
                                            @endif
                                        </select>
                                    </div>
                                    <div class="input-group mg-b-pro-edt">
                                        <span class="input-group-addon ">Vị trí</span>
                                        <input value="{{old('vitri',$dmsp->vitri)}}" type="text" name="vitri" class="form-control" placeholder="Vị trí">
                                    </div>
                                </div>
                                </div>
                            </div>
                        <div style="padding-top: 30px" class="mg-b-pro-edt custom-pro-edt-ds">
                            <button name="addTintuc" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                            </button>
                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                            </button></div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/dmsps/dmsp-list.blade.php
@extends('admin.welcome')
@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{route('index')}}">{{trans('message.trangchu')}}</a> <span class="bread-slash">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.danhsach')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('content')
<div class="product-status mg-tb-15">
    @include('admin.blocks.alert')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>{{trans('message.danhmuc_sanpham')}}</h4>
                    <div class="add-product">
                        <a href="{{ route('dmsp.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                        <table>
                            <tr>
                                <td>
                                    <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                </td>
                                <th>Tên danh mục</th>
                                <th>Vị trí</th>
                                <th>Danh mục</th>
                                <th>Chọn</th>
                            </tr>
                            @foreach($dmsp as $item)
                            <tr style="vertical-align: top">
                                <td>
                                    <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                </td>
                                <td style="width: 32%">{{$item->name}}</td>
                                <td style="width: 20%">{{$item->vitri}}</td>
                                <td style="width: 35%">
                                        @if(empty($item->id_parent))
                                        {{$item->name}}
                                        @else
                                            @foreach($optArr as $opt)
                                                @if($opt['id'] == $item->id_parent)
                                                    {{$opt['name']}}
                                                @endif
                                            @endforeach
                                        @endif 
                               </select>
                                </td>
                                <td style="width: 10%">
                                    <a href="{{ route('dmsp.edit', ['dmsp' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true">{{trans('message.btn_sua')}}</i>
                                    </a>
                                </td>                   
                            </tr>
                            @endforeach
                        </table>
                        {{ method_field('DELETE') }}
                        <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="pd-setting-ed-delete">
                            <i class="fa fa-trash-o" aria-hidden="true"></i> {{trans('message.btn_xoa')}}
                        </button>
                    </form>
                    <div >{{$dmsp->links()}}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection