routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');
	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::post('thay-doi-mat-khau', 'LoginController@postPassword')->name('trangchu.postPassword');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');
	Route::post('thay-doi-dia-chi', 'LoginController@postAddress')->name('trangchu.postAddress');
	Route::get('thay-doi-email', 'LoginController@getChangeEmail')->name('trangchu.getChangeEmail');
	Route::post('thay-doi-email', 'LoginController@postChangeEmail')->name('trangchu.postChangeEmail');
	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');
}); 


Route::namespace('Admin')->group(function(){
	Route::get('login','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('login','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/UseradminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\Useradmins\StoreRequest;
use App\Http\Controllers\Controller;
use App\Model\Useradmin;
use Input;

class UseradminController extends Controller
{
    private $useradmin;


    public function __construct(Useradmin $useradmin)
    {
        $this->useradmin          = $useradmin;

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['useradmin']   = $this->useradmin->index();
        return view('admin.module.useradmin.user-list',$data);    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.module.useradmin.user-create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {
        $data = array(
                        'username' => $req->username,
                        'password' => bcrypt($req->password),
                        'rule' => $req->rule,
                        'fullname' => $req->fullname,
                        'phone' => $req->phone,
                        'email' =>$req->email,
                    ); 
                
        $this->useradmin->store($data);
        return redirect()->back()->with('alertsuc','Thêm useradmin thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['useradmin'] = $this->useradmin->getUser($id);
        return view('admin.module.useradmin.user-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        $data = array(
                        'rule' => $req->rule,
                        'fullname' => $req->fullname,
                        'phone' => $req->phone,
                        'email' =>$req->email,
                    ); 
                
        $this->useradmin->updateUser($data,$id);
        return redirect()->back()->with('alertsuc','Sửa useradmin thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                if($id > 1)
                {
                    $this->useradmin->destroyUser($id);
                }
                else
                {
                    return redirect()->back()->with('alerterr','Vui lòng không xóa admin tổng');
                }
            }
            return redirect()->route('useradmin.index')->with('alertsuc','Xóa user thành công');
        }

    }
}

resources/views/admin/module/useradmin/user-create.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('useradmin.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_them')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
 .lable_edit{
    font-weight: normal;
 }
 .font{
    font-size: 16px;
 }
</style>
<form action="{{ route('useradmin.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a href="#description"><i class="fa fa-pencil" aria-hidden="true"></i> Thông Tin Tài Khoản</a></li>
                        <div id="myTabContent" class="tab-content custom-product-edit">
                            <div class="product-tab-list tab-pane fade active in" id="description">
                                <div class="row">
                                    <div class="font col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="review-content-section">
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Họ tên *</label>
                                                <input value="{{old('fullname')}}" type="text" name="fullname" class="form-control" >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Số điện thoại *</label>
                                                <input value="{{old('phone')}}" type="text" name="phone" class="form-control"  >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                 <label class="lable_edit">Email *</label>
                                                <input value="{{old('email')}}" type="text" name="email" class="form-control" >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Tên đăng nhập *</label>
                                                <input value="{{old('username')}}" type="text" name="username" class="form-control">
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Mật khẩu *</label>
                                                <input value="{{old('password')}}" type="password" name="password" class="form-control">
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Quyền *</label>
                                                <select name="rule" class="form-control pro-edt-select form-control-primary">
                                                    <option value='0' selected="">Admin tổng</option>
                                                        <option value='1'>Admin post</option>
                                                        <option value='2'>Admin product</option>
                                                        <option value='3'>Admin cấp 3</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="mg-b-pro-edt custom-pro-edt-ds">
                                            <button name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
												</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/useradmin/user-edit.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('useradmin.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_sua')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')


<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a href="#description"><i class="fa fa-pencil" aria-hidden="true"></i> Thông Tin Chi Tiết</a></li>                            
                        </ul>
                         <form action="{{route('useradmin.update', ['sanpham' => $useradmin->id]) }}" method="POST" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                        <div id="myTabContent" class="tab-content custom-product-edit">
                            <div class="product-tab-list tab-pane fade active in" id="description">
                                <div class="row">
                                    <div class="font col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="review-content-section">
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Họ tên *</label>
                                                <input value="{{old('fullname',$useradmin->fullname)}}" type="text" name="fullname" class="form-control" >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Số điện thoại *</label>
                                                <input value="{{old('phone',$useradmin->phone)}}" type="text" name="phone" class="form-control"  >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                 <label class="lable_edit">Email *</label>
                                                <input value="{{old('email',$useradmin->email)}}" type="text" name="email" class="form-control" >
                                            </div>
                                            <div class="mg-b-pro-edt">
                                                <label class="lable_edit">Quyền *</label>
                                                <select name="rule" class="form-control pro-edt-select form-control-primary">
                                                    <?php
                                                            $sele = "";
                                                            if($useradmin->rule=="0")
                                                            { ?>
                                                                <option value='0' selected="">Admin</option>
                                                                <option value='1'>Admin post</option>
                                                                <option value='2'>Admin product</option>
                                                                <option value='3'>Admin cấp 3</option>
                                                            <?php }
                                                            else if($useradmin->rule=="1")
                                                            { ?>
                                                                <option value='0'>Admin</option>
                                                                <option value='1' selected="">Admin post</option>
                                                                <option value='2'>Admin product</option>
                                                                <option value='3'>Admin cấp 3</option>
                                                            <?php }
                                                            else if($useradmin->rule=="2")
                                                            { ?>
                                                                <option value='0'>Admin</option>
                                                                <option value='1'>Admin post</option>
                                                                <option value='2' selected="">Admin product</option>
                                                                <option value='3'>Admin cấp 3</option>
                                                            <?php }
                                                            else if($useradmin->rule=="3")
                                                            { ?>
                                                                <option value='0'>Admin</option>
                                                                <option value='1'>Admin post</option>
                                                                <option value='2'>Admin product</option>
                                                                <option value='3' selected="">Admin cấp 3</option>
                                                            <?php }
                                                        ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="text-center mg-b-pro-edt custom-pro-edt-ds">
                                            {{ method_field('PUT') }}
                                            <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                                                </button>
                                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                                                </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/module/useradmin/user-list.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{ route('index') }}">{{trans('message.trangchu')}}</a> <span class="bread-slash">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.danhsach')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="product-status mg-tb-15">
    @include('admin.blocks.alert')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>{{trans('message.danhsach_admin')}}</h4>
                    <div class="add-product">
                        <a href="{{ route('useradmin.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                    <table>
                        <tr>
                            <th>
                                <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                            </th>
                            <th>Mã</th>
                            <th>Họ tên</th>
                            <th>Username</th>
                            <th>Quyền</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Hoạt động</th>
                            <th>Chọn</th>
                        </tr>
                        @foreach($useradmin as $item)
                        <tr>
                            <td >
                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                            </td>
                            <td style="width: 5%">{{$item->id}}</td>
                            <td style="width: 12%">{{$item->fullname}}</td>
                            <td style="width: 13%">{{$item->username}}</td>
                            <td style="width: 15% ">
                                @if($item->rule==0)
                                    Admin
                                @elseif($item->rule==1)
                                    Admin post
                                @elseif($item->rule==2)
                                    Admin product
                                @elseif($item->rule==3)
                                    Admin cấp 3
                                @endif
                            </td>
                            <td style="width: 10%">{{$item->phone}}</td>
                            <td style="width: 25%">{{$item->email}}</td>
                            <td style="width: 10%">
                                    {{convertdate1($item->created_at)}}
                            </td>
                            <td style="width: 10%">
                                <a href="{{ route('useradmin.edit', ['useradmin' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"> {{trans('message.btn_sua')}}</i>
                                </a>
                            </td>                   
                        </tr>
                        @endforeach
                    </table>
                    {{ method_field('DELETE') }}
                    <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="pd-setting-ed-delete">
                        <i class="fa fa-trash-o" aria-hidden="true"></i> {{trans('message.btn_xoa')}}
                    </button>
                    </form>
                     {{$useradmin->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection