routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');
	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::post('thay-doi-mat-khau', 'LoginController@postPassword')->name('trangchu.postPassword');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');
	Route::post('thay-doi-dia-chi', 'LoginController@postAddress')->name('trangchu.postAddress');
	Route::get('thay-doi-email', 'LoginController@getChangeEmail')->name('trangchu.getChangeEmail');
	Route::post('thay-doi-email', 'LoginController@postChangeEmail')->name('trangchu.postChangeEmail');
	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');
}); 


Route::namespace('Admin')->group(function(){
	Route::get('login','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('login','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/NhanxetController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Nhanxets\StoreRequest;
use App\Model\Nhanxet;
use DB;
use Input;
use File;
class NhanxetController extends Controller
{
    private $nhanxet;

    public function __construct(Nhanxet $nhanxet)
    {
        $this->nhanxet          = $nhanxet;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['nhanxet']   = $this->nhanxet->index();
        return view('admin.module.nhanxets.nhanxet-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.module.nhanxets.nhanxet-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {

        $data = array(
                        'fullname' => $req->fullname,
                        'content' => $req->content,
                    );

        if($req->hasFile('photos')) 
        {
        //     //Quy dinh duoi
            $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
            //Lay image
            $file = $req->file('photos');
            //Lay duoi image
            $extension = strtolower($file->getClientOriginalExtension());
            //Kiem tra duoi co trong quy dinh khong
            $check=in_array($extension,$allowedfileExtension);
            if($check) {
                //upload tung image
                $filename = $req->photos->store('nhanxet');
                $data['img'] = $filename;
                $this->nhanxet->storeNhanxet($data);
                return redirect()->back()->with('alertsuc','Thêm thành công');
            }
            else
            {
                return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
            }
        }
        else
        {
            // $data['img'] = "product_default.jpg";
            $this->nhanxet->storeNhanxet($data);
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['nhanxet'] = $this->nhanxet->getNhanxet($id);
        return view('admin.module.nhanxets.nhanxet-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        if (isset($_POST['addTintuc']))
        {
            $data = array(
                        'fullname' => $req->fullname,
                        'content' => $req->content,
                    );
            if($req->hasFile('photos')) 
            {
            //     //Quy dinh duoi
                $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
                //Lay image
                $file = $req->file('photos');
                //Lay duoi image
                $extension = strtolower($file->getClientOriginalExtension());
                //Kiem tra duoi co trong quy dinh khong
                $check=in_array($extension,$allowedfileExtension);
                if($check) {
                    //upload tung image
                    $this->nhanxet->destroyImg($id);
                    $filename = $req->photos->store('nhanxet');
                    $data['img'] = $filename;
                    $this->nhanxet->updateNhanxet($data,$id);
                    return redirect()->back()->with('alertsuc','Sửa thành công');
                }
                else
                {
                    return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
                }
            }
            $this->nhanxet->updateNhanxet($data,$id);
            return redirect()->back()->with('alertsuc','Sửa thành công');
        
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->slide->destroyImg($id);
                $this->slide->destroyNhanxet($id);
            }
            return redirect()->route('nhanxet.index')->with('alertsuc','Xóa thành công');
        }

    }
}

resources/views/admin/module/nhanxets/nhanxet-create.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{route('index')}}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('nhanxet.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_them')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .edit{
        /*background: #EEECEC;*/
        padding: 10px;
        font-size: 26px;
        font-weight: bold;
        /*border-radius: 5px;*/
    }
</style>
<form action="{{ route('nhanxet.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <div class="color-line"></div>
                        <span class="edit">Thêm Bình Luận</span>
                        <div class="color-line"></div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Họ tên</span>
                                            <input value="{{old('fullname')}}" type="text" name="fullname" class="form-control" placeholder="Nhập họ tên">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon ">Hình ảnh</span>
                                            <input type="file" name="photos" class="form-control btn btn-primary  ">                                       
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <div style="margin-top: 45px" class="color-line"></div>
                        <span class="edit">Nội Dung</span>
                        <div class="color-line"></div>
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a style="font-weight: normal;" href="#description"><i class="fa fa-pencil" aria-hidden="true"></i>Nội dung</a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content custom-product-edit">
                            <div class="product-tab-list tab-pane fade active in" id="description">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="review-content-section">
                                            <textarea rows="10" id="editor1" name="content" placeholder="Type the content here!"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div style="padding-top: 30px" class="mg-b-pro-edt custom-pro-edt-ds">
                            <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                            </button>
                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                            </button></div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/nhanxets/nhanxet-edit.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{route('index')}}">{{trans('message.trangchu')}}</a>
                                    <span class="bread-slash">/</span>
                                </li>
                                <li><a href="{{ route('nhanxet.index') }}">{{trans('message.danhsach')}}</a>
                                    <span class="bread-blod">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.btn_sua')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<style type="text/css">
    .edit{
        /*background: #EEECEC;*/
        padding: 10px;
        font-size: 26px;
        font-weight: bold;
        /*border-radius: 5px;*/
    }
</style>
<form action="{{ route('nhanxet.update', ['nhanxet' => $nhanxet->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    {{ method_field('PUT') }}
<div class="single-product-tab-area mg-tb-15">
    @include('admin.blocks.alert')
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <div class="color-line"></div>
                        <span class="edit">Hình ảnh</span>
                        <div class="color-line"></div>
                            <div style="margin-bottom: 50px" class="row">
                                <div class="col-lg-12 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                            @if($nhanxet->img == "default.jpg")
                                            Không có hình ảnh
                                            @else
                                            <img style="width: 150px;height: 100px;float: left;margin: 7px" src="{{ asset('image/'.$nhanxet->img) }}" alt="">
                                            @endif
                                    </div>
                                </div>
                            </div>
                        <div class="color-line"></div>
                        <span class="edit">{{trans('message.btn_sua')}}</span>
                        <div class="color-line"></div>
                           <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon">Họ tên</span>
                                            <input value="{{old('fullname',$nhanxet->fullname)}}" type="text" name="fullname" class="form-control" placeholder="Nhập họ tên">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="input-group mg-b-pro-edt">
                                            <span class="input-group-addon ">Hình ảnh</span>
                                            <input type="file" name="photos" class="form-control btn btn-primary  ">                                       
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <div style="margin-top: 45px" class="color-line"></div>
                        <span class="edit">Nội Dung</span>
                        <div class="color-line"></div>
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a style="font-weight: normal;" href="#description"><i class="fa fa-pencil" aria-hidden="true"></i>Nội dung chi tiết</a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content custom-product-edit">
                            <div class="product-tab-list tab-pane fade active in" id="description">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="review-content-section">
                                            <textarea rows="10" id="editor1" name="content" placeholder="Type the content here!" >
                                                {{$nhanxet->content}}
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div style="padding-top: 30px" class="mg-b-pro-edt custom-pro-edt-ds">
                            
                            <button name="addTintuc" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                            </button>
                            <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                            </button></div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/admin/module/nhanxets/nhanxet-list.blade.php
@extends('admin.welcome')

@section('breadcome')
<div class="breadcome-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list single-page-breadcome">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="margin-top: -23px;">
                            <ul class="breadcome-menu">
                                <li><a href="{{route('index')}}">{{trans('message.trangchu')}}</a> <span class="bread-slash">/</span>
                                </li>
                                <li><span class="bread-blod">{{trans('message.danhsach')}}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="product-status mg-tb-15">
    @include('admin.blocks.alert')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>{{trans('message.danhsach_nhanxet')}}</h4>
                    <div class="add-product">
                        <a href="{{ route('nhanxet.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                    <table>
                        <tr>
                            <td>
                                <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                            </td>
                            <th>Họ tên</th>
                            <th>Hình ảnh</th>
                            <th>Nội dung</th>
                            <th>Chọn</th>
                        </tr>
                        @foreach($nhanxet as $item)
                        <tr>
                            <td >
                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                            </td>
                            <td style="width: 25%">{{$item->fullname}}</td>
                            <td style="width: 25%">
                                <img style="width: 90px" src="{{ asset('image/'.$item->img) }}" alt="">
                            </td>
                            <td style="width: 40%">{{$item->content}}</td>
                            <td style="width: 10%">
                                <a href="{{ route('nhanxet.edit', ['nhanxet' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                    <i class="fa fa-pencil-square-o clear" aria-hidden="true">Sửa</i>
                                </a>
                            </td>                   
                        </tr>
                        @endforeach
                    </table>
                    {{ method_field('DELETE') }}
                    <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="pd-setting-ed-delete">
                        <i class="fa fa-trash-o" aria-hidden="true"></i> Xóa
                    </button>
                    </form>
                     {{$nhanxet->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection